const test=require('node:test');
const assert=require('node:assert/strict');
const BASE=process.env.TEST_BASE_URL||'http://localhost:8180';
async function request(path,options={}){const response=await fetch(BASE+path,{...options,headers:{...(options.body?{'Content-Type':'application/json'}:{}),...(options.token?{Authorization:`Bearer ${options.token}`}:{})}});const text=await response.text();let data;try{data=JSON.parse(text)}catch{data=text}return{status:response.status,data,headers:response.headers}}
let token,citaId,fecha,hora,psychToken,maintenanceToken;
let managedUserId,noteId;
test('health confirma PostgreSQL y Redis',async()=>{const r=await request('/health');assert.equal(r.status,200);assert.equal(r.data.status,'healthy');assert.equal(r.data.checks.postgres,'ok');assert.equal(r.data.checks.redis,'ok')});
test('registro entrega JWT',async()=>{const r=await request('/api/v1/auth/register',{method:'POST',body:JSON.stringify({nombre:'Prueba',apellido:'Agenda',email:`agenda.${Date.now()}@example.com`,password:'PruebaSegura123',telefono:'3007654321'})});assert.equal(r.status,201);assert.ok(r.data.data.accessToken);token=r.data.data.accessToken});
test('cuentas gestionadas inician sesión con roles separados',async()=>{const psych=await request('/api/v1/auth/login',{method:'POST',body:JSON.stringify({email:process.env.PSYCHOLOGIST_EMAIL||'psicologa@psicologaluz.local',password:process.env.PSYCHOLOGIST_PASSWORD||'PsicologaLocal2026!'})});const maintenance=await request('/api/v1/auth/login',{method:'POST',body:JSON.stringify({email:process.env.MAINTENANCE_EMAIL||'mantenimiento@psicologaluz.local',password:process.env.MAINTENANCE_PASSWORD||'MantenimientoLocal2026!'})});assert.equal(psych.status,200);assert.equal(psych.data.data.user.rol,'psicologa');assert.equal(maintenance.status,200);assert.equal(maintenance.data.data.user.rol,'superadmin');psychToken=psych.data.data.accessToken;maintenanceToken=maintenance.data.data.accessToken});
test('permisos clínicos y técnicos están separados',async()=>{const clinical=await request('/api/v1/clinical/resumen',{token:psychToken});const deniedClinical=await request('/api/v1/clinical/resumen',{token:maintenanceToken});const maintenance=await request('/api/v1/maintenance/estado',{token:maintenanceToken});const deniedMaintenance=await request('/api/v1/maintenance/estado',{token:psychToken});assert.equal(clinical.status,200);assert.equal(deniedClinical.status,403);assert.equal(maintenance.status,200);assert.equal(deniedMaintenance.status,403)});
test('superadmin crea, edita y elimina usuarios',async()=>{const stamp=Date.now();const created=await request('/api/v1/maintenance/usuarios',{method:'POST',token:maintenanceToken,body:JSON.stringify({nombre:'Usuario',apellido:'Gestionado',email:`gestion.${stamp}@example.com`,password:'TemporalSegura123!',rol:'recepcionista'})});assert.equal(created.status,201);managedUserId=created.data.data.id;const edited=await request(`/api/v1/maintenance/usuarios/${managedUserId}`,{method:'PUT',token:maintenanceToken,body:JSON.stringify({nombre:'Usuario Editado',apellido:'Gestionado',email:`gestion.${stamp}@example.com`,rol:'paciente',activo:true})});assert.equal(edited.status,200);assert.equal(edited.data.data.rol,'paciente');const removed=await request(`/api/v1/maintenance/usuarios/${managedUserId}`,{method:'DELETE',token:maintenanceToken});assert.equal(removed.status,200);assert.equal(removed.data.data.activo,false)});
test('paciente puede entrar y salir de lista de espera',async()=>{const created=await request('/api/v1/lista-espera',{method:'POST',token,body:JSON.stringify({modalidad:'virtual',fecha_desde:new Date(Date.now()+7*86400000).toISOString().slice(0,10),preferencias:'Tardes'})});assert.equal(created.status,201);const list=await request('/api/v1/lista-espera',{token});assert.ok(list.data.data.some(x=>x.id===created.data.data.id));const removed=await request(`/api/v1/lista-espera/${created.data.data.id}`,{method:'DELETE',token});assert.equal(removed.status,200)});
test('panel operativo, registro clínico y PWA están publicados',async()=>{const panel=await fetch(BASE+'/panel.html');const session=await fetch(BASE+'/sesion-clinica.html');const manifest=await fetch(BASE+'/manifest.webmanifest');assert.equal(panel.status,200);assert.match(await panel.text(),/Panel operativo/);assert.equal(session.status,200);assert.match(await session.text(),/Registro de sesión clínica/);assert.equal(manifest.status,200)});
test('cita creada aparece aunque antes se haya cacheado otro filtro',async()=>{fecha=new Date(Date.now()+21*86400000).toISOString().slice(0,10);const disp=await request(`/api/v1/disponibilidad/slots?fecha=${fecha}&modalidad=virtual`);assert.equal(disp.status,200);assert.ok(disp.data.data.length);hora=disp.data.data[0].hora;const create=await request('/api/v1/citas',{method:'POST',token,body:JSON.stringify({fecha,hora_inicio:hora,modalidad:'virtual',motivo:'Regresión listado agenda'})});assert.equal(create.status,201);citaId=create.data.data.id;const empty=await request('/api/v1/citas?desde=2035-01-01',{token});assert.equal(empty.status,200);assert.equal(empty.data.data.some(c=>c.id===citaId),false);const visible=await request(`/api/v1/citas?desde=${new Date().toISOString().slice(0,10)}`,{token});assert.equal(visible.status,200);assert.ok(visible.data.data.some(c=>c.id===citaId),'La cita recién creada debe aparecer en Mis próximas citas')});
test('calendario ICS pertenece a la cita creada',async()=>{const r=await request(`/api/v1/citas/${citaId}/calendario.ics`,{token});assert.equal(r.status,200);assert.match(r.data,/BEGIN:VCALENDAR/);assert.match(r.data,new RegExp(citaId))});
test('psicóloga registra, firma, protege, verifica y exporta informe clínico PDF',async()=>{const created=await request(`/api/v1/notas/${citaId}`,{method:'POST',token:psychToken,body:JSON.stringify({contenido:'Sesión de prueba automatizada con evaluación del estado emocional.',estado_animo:7,progreso:4,tareas_asignadas:'Ejercicio de respiración',next_steps:'Seguimiento en próxima sesión'})});assert.equal(created.status,201);noteId=created.data.data.id;const context=await request(`/api/v1/notas/cita/${citaId}/contexto`,{token:psychToken});assert.equal(context.status,200);assert.equal(context.data.data.nota_id,noteId);const signed=await request(`/api/v1/notas/documento/${noteId}/firmar`,{method:'POST',token:psychToken});assert.equal(signed.status,200);assert.match(signed.data.data.firma_hmac,/^[a-f0-9]{64}$/);const protectedDoc=await request(`/api/v1/notas/documento/${noteId}/proteger`,{method:'POST',token:psychToken});assert.equal(protectedDoc.status,200);assert.ok(protectedDoc.data.data.protegido_at);const verify=await request(`/api/v1/notas/documento/${noteId}/verificar`,{token:psychToken});assert.equal(verify.status,200);assert.equal(verify.data.data.valida,true);const pdf=await request(`/api/v1/notas/documento/${noteId}/pdf`,{token:psychToken});assert.equal(pdf.status,200);assert.match(pdf.data,/^%PDF/)});
test('sala virtual permanece cerrada fuera de la ventana segura',async()=>{const r=await request(`/api/v1/citas/${citaId}/sala`,{token});assert.equal(r.status,403);assert.match(r.data.message,/30 minutos/i)});
test('cancelar libera nuevamente el horario',async()=>{const cancel=await request(`/api/v1/citas/${citaId}`,{method:'DELETE',token,body:JSON.stringify({motivo_cancelacion:'Limpieza prueba'})});assert.equal(cancel.status,200);const disp=await request(`/api/v1/disponibilidad/slots?fecha=${fecha}&modalidad=virtual`);assert.equal(disp.status,200,JSON.stringify(disp.data));assert.ok(disp.data.data.some(s=>s.hora===hora))});
